Repository yusancky/Satwiki-Improvement-Project, pull requests merged in 2022-08, with the labels that each got.

#5 Update README.md
  README.md
Labels: documentation

#8 Fix Comparison_satellite_navigation_orbits.svg
  file/Comparison_satellite_navigation_orbits/Comparison_satellite_navigation_orbits.svg
Labels: 需要修改

#10 Prapare for Public
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/docs-cn.md
  README.md
  i18n/README/README-en.md
  i18n/README/README-jp.md
Labels: 文档

#13 Create README-fr.md
  i18n/README/README-en.md
  i18n/README/README-fr.md
  i18n/README/README-jp.md
Labels: 文档翻译

#12 Update README.md
  README.md
Labels: 文档翻译
